# .travis.yml
language: node_js
script: 'true'

node_js:
  - "lts/*"

os: windows

branches:
  only:
    - master

install:
  - npm install yarn electron webpack typescript -g

script:
  - yarn install