name: Deploy

on:
  release:
    types:
      - created

jobs:
  build:
  
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'npm'

    - name: Update npm
      run: npm install --global npm@latest

    - name: Patch node-gyp to support Visual Studio 2019
      shell: powershell
      run: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
          
    - name: Install Global Dependencies
      run: npm install yarn electron webpack typescript -g

    - name: Install Dependencies & Build Native Files
      run: yarn install

    - name: Build Typescript files
      run: yarn run build
        
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
